resolver: lts-8.0

docker:
  enable: true

packages:
- '.'
- location:
    git: git@github.com:CthulhuDen/slack-api.git
    commit: dd8608d5b3c178286e01e9da2b425694dfab917f
  extra-dep: true
- location:
    git: git@github.com:CthulhuDen/slack-rtm-state.git
    commit: 261390a0460b57f6d8dfe1ddb69a57748cc7d3fd
  extra-dep: true

extra-deps:
- 'wreq-0.5.0.0'
- 'distributed-process-client-server-0.1.3.2'
- 'distributed-process-extras-0.2.1.2'
- 'distributed-process-async-0.2.3'


# Override default flag values for local packages and extra-deps
flags: {}
